### ISSUE TITLE
Syntax error in `db/upgrade.php`

### ISSUE THREAD

**Issue by daniil-berg** [eberhardt/moodle-block_coursefeedback#16]
That dot in line 23 must have been a typo.

https://github.com/eberhardt/moodle-block_coursefeedback/blob/a8aa452cbef07155cc74235a51c8dd40770893e5/db/upgrade.php#L17-L25

**Comment by eberhardt** [comment]
Thanks for reporting, it's fixed!
Must have been slipped through review process.
