### ISSUE TITLE
Version incrementation

### ISSUE THREAD

**Issue by eberhardt** [eberhardt/moodle-block_coursefeedback#19]
In [MOODLE_401_V2-BETA](/eberhardt/moodle-block_coursefeedback/tree/MOODLE_401_V2-BETA) and since [MOODLE_411_V2-BETA](/eberhardt/moodle-block_coursefeedback/tree/MOODLE_311_V2-BETA) _MATURITY\_STABLE_ and "v2.1.0" is used in version.php.
With such large changes, however, at least a major release should be jumped (3.x.y) and, since we are still running it as a beta, the maturity should also be adjusted, as long as this does not have any undesirable consequences during installation (e.g. warnings or the like). Please fix that and set a reasonable version above 3.0.0 for the latest version (after PRs).

For increment jumps, the readable version should always be incremented from now on, too.

**Comment by FelixDiLenarda** [comment]
Issue fixed with merge of  #21
