### ISSUE TITLE
About the zh_cn language problem

### ISSUE THREAD

**Issue by Romantic-Jacky** [eberhardt/moodle-block_coursefeedback#3]
Hi Jan

Thanks for your guide. I am now posting issue right here at Github.

Firstly, the character encoding of my site is UTF-8. 

And, Secondly, I found the sources of the problems may came from the admin.php page.I followed your suggestion, opened the debug mode on my site. And I notice the debug message at the adding questions page as follow:
------------------------------------------------------------------------------------------
Notice: Undefined variable: url1 in /home/www/course/blocks/coursefeedback/admin.php on line 578
------------------------------------------------------------------------------------------

My parameters of the url is: xxx/blocks/coursefeedback/admin.php?mode=questions&action=new&fid=2&qid=0

Still, when I add a question in the admin setting page, I can not add any of that into this language. But somehow, the language "en" is good to use, questions could be added into it.

And even I added some questions manually in mysql database. The whole system seems good to run, but at the final stage, when I view the results of the statistics, there are no data to display, but the frame and the table is there and seem right.

So, I am here for the help, thanks and look forward to hear from you. 

Many thanks, good plugins. I am going to add the Chinese translation for this plugins no matter the problem can be fix or not...

Really thanks and Best regards.

**Comment by eberhardt** [comment]
Also the notice 'Undefined variable' is from outdated code. I fixed this issue a while ago, but just updated the git repo. I forgot to upload the fixed code in a zip file. This is now done. You'll find the same code as here in the Moodle Plugin Directory.

**Comment by Romantic-Jacky** [comment]
oh, thank you so much... i am going to check... and also start the translation for your plugin.
