### ISSUE TITLE
bug: csv download in view.php shows a zero where there shouldn't be one

### ISSUE THREAD

**Issue by FelixDiLenarda** [eberhardt/moodle-block_coursefeedback#37]
Question | very good | good | satisfactory | sufficient | deficient | insufficient | Average | Number of votes | Abstentions

The download shows a zero at the average colum.

**Comment by eberhardt** [comment]
There must be an instance where the average field is not set correctly: 0 is most likely the cast from **null** to int.

**Comment by FelixDiLenarda** [comment]
The problem was that the "Abstentions" were added to the array first, and only afterwards "average" and "Number of votes". When exporting the CSV file, the array is then passed unchanged to the CSV writer, so the "average" was not at the end but in the wrong place, pushing the other two values one position back.
