### ISSUE TITLE
Error writing to database 

### ISSUE THREAD

**Issue by ahsanf** [eberhardt/moodle-block_coursefeedback#9]
Error writing to database when checkbox Stick It  Checked on Moodle 3.8.x

![image](https://user-images.githubusercontent.com/47440504/114354456-78442c00-9b98-11eb-8e03-de4596c90276.png)

**Comment by eberhardt** [comment]
Hi,
never managed to check this bug, but you used my utterly outdated code on a - to that time - recent Moodle version. I'm not surprised it didn't work.
Since we got a new version for Moodle 4.x running we will close this issue. Thanks for reporting, anyway!

Kind regards
Jan
